#!/bin/sh

# Execution hook dvc si disponible
if command -v dvc &> /dev/null
then
	echo -e "[DVC] - Execution hook 'post-checkout'\n"
	exec dvc git-hook post-checkout $@
else
	echo -e "[DVC] - Attention la commande 'dvc' n'est pas disponible. On skip DVC. \n"
fi